### ISSUE TITLE
Image Generation

### ISSUE THREAD

**Issue by cj-chua** [nostr-protocol/data-vending-machines#6]
Hey @believethehype , I have some questions/observations on the image gen job request.

The combination of `ratio` and `upscale` does not seem to cover the case where a client wants an output image of a specific size. (i.e. 900x300). We have this use case on tasktiger.io, where a jobchain needs to know the size of the image to be generated.

A couple proposal I could think of
1. Go back to the old way of using ["param", "size", "900x300"]. This way any arbitrary size could be supported
2. Keep `ratio` and remove `upscale`. Create a new `image upscaling` job type that accepts the final dimension (px) as a param. To generate an image of a specific dimension(px), clients have to specify the ratio during image generation, and then feed the output to the image upscaling job to get the exact dimension as desired.

Mostly thinking out loud here, what do you think?

**Comment by cj-chua** [comment]
@pablof7z would love your opinion too

**Comment by believethehype** [comment]
Hi, thanks for bringing this up. It is indeed a bit an uncleared question.

There's a tradeoff between using output size in px and a ratio. My main consideration for going with ratio instead of pixels in the current version of the generation is the arbitrary possibilities of user inputs. 

Some aspects include:
- Models are trained on, and produce different output sizes. Users likely do not know, nor care about what a model they select might work best on (or at all), so basically for each model you first need to internally map the desired output to a range the model supports, then:
- Not all models support all kinds of ratios. E.g. If you work with pixels and a user wants a 1723x627 pixel output, models are likely to fail to produce that. So you would need to estimate the closest allowed ratio/pixels first and then resize to the exact output.
- Same is indeed true for working with ratios, but by limiting the set of ratios (1:1, 4:3, 16:9, 16:10, ??, 3:4.. etc) we can avoid extreme ratios that are not supported, compared to pixels that can be freely entered.
- Often users want the best possible resolution and they don't want to calculate pixel times pixel. Most people do understand what a 16:9 ratio is tho, so ratio is imo easier for users to deal with.

Does that make sense to you? I do understand tho that there might be cases where you want/need the exact output pixels.

First of all I agree that we probably should get rid of the upscale param (for reasons mentioned above), and having a image-upscale kind of its own would make sense, especially as it can be used on any image, not only generated ones, which is a nice dvm task per se (Image generation might still internally upscale if only highest resolution was to remain the target)

An upscale-image task could have params like the upscale "factor" (2x, 4x) or, as you mentioned a param "size" that overwrites factor and resizes the final output to that exact resolution. Just something to keep in mind, if that resolution drifts too far from the ratio of the input image, you would also need to consider working with different resize methods like, stretch, crop etc.


(In another topic, I tend more and more to also have an own kind for image-to-image processing, due to different inputs and options that are used compared to generation, what do you think about that?)

**Comment by cj-chua** [comment]
Yes it makes sense that trying to achieve fixed dimension from a ratio would cause distortion. 

However there are models that could support arbitrary ratio, for example Midjourney, in which it'll be integrated into TaskTiger. And to support generating images with arbitrary ratio, the desired final size has to be specified in the image gen request itself (cause as discussed scaling it later causes distortion). So the upscale service provider proposal doesn't seem to work for fixed size image use case.

To that I think for now I'll continue to reuse the `size` param with this kind

**Comment by believethehype** [comment]
Merged
